## This Workflow creates a basic jira bug and updates in Port
## Remove comments and edit for more fields as part of the jira bug

name: Report a bug in jira

on:
  workflow_dispatch:
    inputs:
      description:
        required: true
        type: string
      short_title:
        required: true
        type: string
#     priority:
#       required: true
#       type: string
#     custom_12345:
#     required: false
#     type: string
      port_payload:
        required: true
        type: string

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Inform starting of jira issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        runId: ${{ fromJson(inputs.port_payload).context.runId }}
        logMessage: |
            Creating a new Jira issue.. ⛴️

    - name: Create Jira issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: ENTER_JIRA_PROJECT_NAME
        issuetype: Bug
        summary:  Bug | ${{github.event.inputs.short_title}}
        description: |
          ${{github.event.inputs.description}}

        # Custom fields example
        # fields: '{"priority": {"name": "${{inputs.priority}}"}, "custom_12345": "label label"}'


    - name: Inform creation of Jira issue
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: https://getport.atlassian.net/browse/${{ steps.create.outputs.issue }}
        runId: ${{ fromJson(inputs.port_payload).context.runId }}
        logMessage: |
           Jira issue created! ✅
           The issue id is: ${{ steps.create.outputs.issue }}